version: "3.9"

services:
  app:
    build: .
    command: npm start
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  caddy:
    image: caddy:2.4.5-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app
