name: Build

on: [push]

jobs:
  builds:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: devops-for-programmers-project-lvl1
    steps:
      - name: Check out Repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Cache Docker layer
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('**/Dockerfile') }}
          restore-keys: ${{runner.os}}-buildx-

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.production
          builder: ${{steps.buildx.outputs.name}}
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: ${{secrets.DOCKER_HUB_USERNAME}}/${{env.DOCKER_IMAGE_NAME}}:latest
          outputs: type=docker,dest=/tmp/${{env.DOCKER_IMAGE_NAME}}.tar

      - name: Load docker images from archive
        run: |
          docker load < /tmp/${{env.DOCKER_IMAGE_NAME}}.tar

      - name: Run tests
        run: |
          docker run --rm ${{secrets.DOCKER_HUB_USERNAME}}/${{env.DOCKER_IMAGE_NAME}}:latest npm test

      - name: Push image to registry
        run: |
          docker push ${{secrets.DOCKER_HUB_USERNAME}}/${{env.DOCKER_IMAGE_NAME}}:latest

      # - name: Move cache
      #   run: |
      #     rm -rf /tmp/.buildx-cache
      #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache
